[package]
name = "alcro"
version = "0.5.4"
authors = ["Srinivasa <m.srinivasa1234@gmail.com>"]
edition = "2024"
description = "A library to create desktop apps using rust and modern web technologies"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Srinivasa314/alcro"

[[test]]
name = "integration_test"

[[test]]
name = "tokio_test"
required-features = ["tokio"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"
tinyfiledialogs = "3"
libc = "0.2"
dashmap = "6"
thiserror = "2"
tempfile = "3"
nix = { version = "0.30", features = ["signal", "process", "fs"] }

tokio = { version = "1", features = ["rt"], optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["namedpipeapi", "synchapi", "handleapi", "errhandlingapi", "fileapi", "processthreadsapi", "winbase"] }

[dev-dependencies]
actix-web = "4"
actix-rt = "2"
rust-embed = "8"
mime_guess = "2"
futures = "0.3"
anyhow = "1"

tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
